name: nippon_dost
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0+1
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:  # for state management
  get_storage:  #  for get storage
  qr_flutter:  # for qr image
  qr_code_scanner: 1.0.1 # for qr code scanner
  firebase_core:  # for firebase core libraries
  firebase_messaging:  # for firebase messaging
  flutter_local_notifications: ^9.3.0 # for displaying push notification
  responsive_framework:  # for responsivness on multiple screens
  flutter_screenutil:  # for adapting screen sizes
  line_icons:  # for extra icons
  http:  # for api calls
  rxdart:  # extends the capabilities of streams
  web_socket_channel: #  web sockets for listen data
  flutter_native_splash: ^2.2.9 # for native splash
  shared_preferences: ^2.0.15
  intl: ^0.17.0

# zee
  image_picker: ^0.8.6 # for picking user profile image to show and to upload
  permission_handler: # to ask for permission for gallery image picking
  webview_flutter: ^3.0.0  # to display webview for
  cached_network_image: ^3.2.0 # for promotional image
#  date_range_picker:  # for picking filtering dates not support null safety
  pull_to_refresh: ^2.0.0 # to implement pull down to refresh at dashboard
  syncfusion_flutter_datepicker: ^20.2.50 # to implement range Picker
  file_picker: ^5.2.0 # to send file with support message API
  fluttertoast: ^8.0.8 # to show toast message for coming soon modules
  html: ^0.15.0
  awesome_notifications: ^0.7.3

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/images/general/
     - assets/images/login/
     - assets/images/icons/
     - assets/images/dashboard/
     - assets/images/profile/
     - assets/images/gift_slab/
     - assets/images/history/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
